# Generated by Django 5.2.6 on 2025-09-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['title'],
            },
        ),
    ]
