# Generated by Django 5.2.6 on 2025-09-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['id'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
